# Generated by Django 5.1.2 on 2024-12-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user_fav_track',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='game_score',
            field=models.IntegerField(default=0),
        ),
    ]
